---
title: "Birthday"
output: rmarkdown::html_vignette
vignette: >
  %\VignetteIndexEntry{Birthday}
  %\VignetteEngine{knitr::rmarkdown}
  %\VignetteEncoding{UTF-8}
---

```{r, include = FALSE}
knitr::opts_chunk$set(
  collapse = TRUE,
  comment = "#>"
)
```

```{r setup}
library(MATH4753NUNN2025)
```

# Questions

## 1)
### Derivation

$A$ = {2 or more people have the same birthday}

$A^C$ = {every person has a different birthday}

$$1 = P(A) + P(A^C)$$


$$P(A^C) = \frac{365 \times 364 \times ... \times(365-n+1)}{365^n}$$


$$P(A) = 1 - P(A^C)$$


$$P(A) = 1- \frac{365 \times 364 \times ... \times(365-n+1)}{365^n}$$



## 2)
### Reformulation

From the numerator of $P(A^C)$.
$$365 \times 364 \times ... \times(365-n+1)$$

$$^{365}P_n = n! {}^{365}C_n$$

$$P(A^c) = \frac{{}^{365}P_n }{365^n} $$


$$\begin{aligned} 
logP(A^C) &= log{}^{{}^{365}}P_n - nlog365 \\ &= log(n!) + lchoose(365,n) - nlog(365) \\ &= lfactorial(n) +lchoose(365, n) - nlog(365)
\end{aligned}$$



$$\begin{aligned}
P(A) = 1-P(A^C) &= 1 - exp(log(P(A^C))) \\ &= 1- exp(lfactorial(n) + lchoose(365,n) - nlog(365))
\end{aligned}$$



## 3)
### Show the R function
```{r}
#birthday function
birthday <- function(x){
  1 - exp(lchoose(365,x) + lfactorial(x) - x*log(365))
}

```



## 4)
```{r}
#using the birthday function from package
birthday(20:25)

```


